// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdtbarkfquiaklbqxgkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdGJhcmtmcXVpYWtsYnF4Z2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjU1NzAsImV4cCI6MjA2NzIwMTU3MH0.EawhQVw1aDbSpMCe-_0WkbdtkBZoJ-rIbJoX2eO4w2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});